name: Java Maven Build & Publish Artifact

on:
  [workflow_dispatch]

  runs-on: ubuntu-latest

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml


    publish_job:
      runs-on: ubuntu-latest
      needs: build_job
      steps:
      - uses: actions/checkout@v4
      - uses: action/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
